### PR TITLE
Add Houston Lab Structure

### PR DESCRIPTION
**Pull request by jwo**
I love this way of building projects.

week 1: data parsing from CSV
week 2: Blackjack
week 3: surf and paddle
week 4: surf and paddle in Rails
week 5: Reddit
week 6: Twitter
week 7: Pinterest
week 8: Amazon

### CODE REVIEW

**Comment by jah2488** [comment]
Love the long from projects idea :+1:

**Comment by brianburridge** [comment]
Just assigned Pinterest in week 5. Excited! Great list. Thanks for sharing!

**Comment by jamesdabbs** [comment]
Awesome. :+1:

I'm totally stealing the Amazon one here in a week or two. Haven't used `payola` before. Any tips? Is that a good jumping-off point for discussing Rails engines?

**Comment by jwo** [comment]
@jamesdabbs thanks!!! Payola is fairly new, last couple of months. It does EVERYTHING right -- uses active job so the main thread doesn't block, makes sure purchases won't happen twice.

I didn't go into engines (though I think rails_admin is the perfect point for that). But I did go:

1) standard form with stripe.js
2) stripe checkout 
3) payola awesome button 

It's no surprised they liked 3.

**Pull request merged**
