### PR TITLE
Add several assignments

### PR DESCRIPTION
**Pull request by jamesdabbs**
Wrote up several assignment ideas for the upcoming week (many of these will end up being the in-class projects, but depending on how you present it, they'd be fine for homework).

I'm happy to split these up and make separate PRs for these if anything is contentious / needs to be discussed separately, but that seemed like overkill.

### CODE REVIEW

**Comment by jwo** [comment]
I think these look very cool @jamesdabbs . My question: should we adopt a naming scheme? Or, should we have in the keywords if this is a:

* Quiz
* Assignment
* Lab?

**Comment by jamesdabbs** [comment]
Yeah, I'm open to suggestions. @masonfmatthews has an "assignment /
exercise / puzzle (formerly quiz, but I like the change) / project"
distinction ... I'm not necessarily sure what makes an exercise, but some
sort of terminology there would be good.

Also, we probably want some sort of standardization of tags at some point
if they're going to be searchable. I really had no idea what to put there
for now.

**Comment by jwo** [comment]
Yay! I think the directories per type makes hella sense. 




Do you want to merge and then move? Or move and then merge?

**Comment by masonfmatthews** [comment]
Jesse/James -

A few points on my repo, in case it helps:

1) I had changed "quizzes" to "puzzles", but I changed it again to
"challenges."  Puzzles never felt natural to say, but challenges does, and
the students seem to gravitate towards it, so I'm sticking with Challenges
for now.

2) Exercises are in-lecture mini-assignments, when I'm presenting some
topic and then asking them to immediately try to implement something using
that topic.  Bigger than Challenges, shorter than Assignments.

So yeah, overall my nomenclature is:

   - *Challenges* = first thing in the morning, meant to keep them fresh on
   pure Ruby, started week 5.
   - *Exercises* = mid-lecture tasks to work on implementing an example of
   what we just learned.  Used them in weeks 1-3.
   - *Assignments* = one-night assignments.  Mostly done individually,
   occasionally done in pairs when in support of a bigger project.
   - *Projects* = weekend assignments.  Mostly done in pairs, although
   Battleship was week 1 as individuals and Survey Opossum was week 5 in
   groups of 4 (crossover project with Front End Engineering.

Hope that helps.  Sorry for not having spent any time merging into the org
repo yet... I just don't have any time left!  I also go back shortly after
assigning each one of these and make edits to improve them for the next
cohort, so they're highly in flux.

Thanks,

-----
Mason F. Matthews
Instructor, Durham Campus
The Iron Yard | Smashing Boxes

mason.matthews@theironyard.com
C: (919) 302-5139

**Comment by jwo** [comment]
Awesome, I think I like challenges a WHOLE LOT.

**Comment by redline6561** [comment]
Yo, killer stuff @jamesdabbs! <3

**Pull request merged**
